import { Router } from "express";
import CfopRoute from "./cfop_routes";
import ClienteRoute from "./cliente_routes";
import ClienteFiadoRoute from "./cliente_fiado_routes";
import ColaboradorRoute from "./colaborador_routes";
import CompraPedidoCabecalhoRoute from "./compra_pedido_cabecalho_routes";
import CompraPedidoDetalheRoute from "./compra_pedido_detalhe_routes";
import ContadorRoute from "./contador_routes";
import ContasPagarRoute from "./contas_pagar_routes";
import ContasReceberRoute from "./contas_receber_routes";
import EcfAliquotasRoute from "./ecf_aliquotas_routes";
import EcfDocumentosEmitidosRoute from "./ecf_documentos_emitidos_routes";
import EcfE3Route from "./ecf_e3_routes";
import EcfImpressoraRoute from "./ecf_impressora_routes";
import EcfLogTotaisRoute from "./ecf_log_totais_routes";
import EcfR01Route from "./ecf_r01_routes";
import EcfR02Route from "./ecf_r02_routes";
import EcfR03Route from "./ecf_r03_routes";
import EcfR06Route from "./ecf_r06_routes";
import EcfR07Route from "./ecf_r07_routes";
import EcfRecebimentoNaoFiscalRoute from "./ecf_recebimento_nao_fiscal_routes";
import EcfRelatorioGerencialRoute from "./ecf_relatorio_gerencial_routes";
import EcfSintegra60aRoute from "./ecf_sintegra_60a_routes";
import EcfSintegra60mRoute from "./ecf_sintegra_60m_routes";
import EmpresaRoute from "./empresa_routes";
import EmpresaCnaeRoute from "./empresa_cnae_routes";
import EmpresaSegmentoRoute from "./empresa_segmento_routes";
import FidelidadeHistoricoRoute from "./fidelidade_historico_routes";
import FidelidadeUtilizadoRoute from "./fidelidade_utilizado_routes";
import FornecedorRoute from "./fornecedor_routes";
import IbptRoute from "./ibpt_routes";
import LogImportacaoRoute from "./log_importacao_routes";
import NfcePlanoPagamentoRoute from "./nfce_plano_pagamento_routes";
import NfeAcessoXmlRoute from "./nfe_acesso_xml_routes";
import NfeCabecalhoRoute from "./nfe_cabecalho_routes";
import NfeCanaRoute from "./nfe_cana_routes";
import NfeCanaDeducoesSafraRoute from "./nfe_cana_deducoes_safra_routes";
import NfeCanaFornecimentoDiarioRoute from "./nfe_cana_fornecimento_diario_routes";
import NfeConfiguracaoRoute from "./nfe_configuracao_routes";
import NfeCteReferenciadoRoute from "./nfe_cte_referenciado_routes";
import NfeCupomFiscalReferenciadoRoute from "./nfe_cupom_fiscal_referenciado_routes";
import NfeDeclaracaoImportacaoRoute from "./nfe_declaracao_importacao_routes";
import NfeDestinatarioRoute from "./nfe_destinatario_routes";
import NfeDetalheRoute from "./nfe_detalhe_routes";
import NfeDetalheImpostoCofinsRoute from "./nfe_detalhe_imposto_cofins_routes";
import NfeDetalheImpostoCofinsStRoute from "./nfe_detalhe_imposto_cofins_st_routes";
import NfeDetalheImpostoIcmsRoute from "./nfe_detalhe_imposto_icms_routes";
import NfeDetalheImpostoIcmsUfdestRoute from "./nfe_detalhe_imposto_icms_ufdest_routes";
import NfeDetalheImpostoIiRoute from "./nfe_detalhe_imposto_ii_routes";
import NfeDetalheImpostoIpiRoute from "./nfe_detalhe_imposto_ipi_routes";
import NfeDetalheImpostoIssqnRoute from "./nfe_detalhe_imposto_issqn_routes";
import NfeDetalheImpostoPisRoute from "./nfe_detalhe_imposto_pis_routes";
import NfeDetalheImpostoPisStRoute from "./nfe_detalhe_imposto_pis_st_routes";
import NfeDetEspecificoArmamentoRoute from "./nfe_det_especifico_armamento_routes";
import NfeDetEspecificoCombustivelRoute from "./nfe_det_especifico_combustivel_routes";
import NfeDetEspecificoMedicamentoRoute from "./nfe_det_especifico_medicamento_routes";
import NfeDetEspecificoVeiculoRoute from "./nfe_det_especifico_veiculo_routes";
import NfeDuplicataRoute from "./nfe_duplicata_routes";
import NfeEmitenteRoute from "./nfe_emitente_routes";
import NfeExportacaoRoute from "./nfe_exportacao_routes";
import NfeFaturaRoute from "./nfe_fatura_routes";
import NfeImportacaoDetalheRoute from "./nfe_importacao_detalhe_routes";
import NfeInformacaoPagamentoRoute from "./nfe_informacao_pagamento_routes";
import NfeItemRastreadoRoute from "./nfe_item_rastreado_routes";
import NfeLocalEntregaRoute from "./nfe_local_entrega_routes";
import NfeLocalRetiradaRoute from "./nfe_local_retirada_routes";
import NfeNfReferenciadaRoute from "./nfe_nf_referenciada_routes";
import NfeNumeroRoute from "./nfe_numero_routes";
import NfeNumeroInutilizadoRoute from "./nfe_numero_inutilizado_routes";
import NfeProcessoReferenciadoRoute from "./nfe_processo_referenciado_routes";
import NfeProdRuralReferenciadaRoute from "./nfe_prod_rural_referenciada_routes";
import NfeReferenciadaRoute from "./nfe_referenciada_routes";
import NfeResponsavelTecnicoRoute from "./nfe_responsavel_tecnico_routes";
import PdvCaixaRoute from "./pdv_caixa_routes";
import PdvConfiguracaoRoute from "./pdv_configuracao_routes";
import PdvConfiguracaoBalancaRoute from "./pdv_configuracao_balanca_routes";
import PdvConfiguracaoLeitorSerialRoute from "./pdv_configuracao_leitor_serial_routes";
import PdvFechamentoRoute from "./pdv_fechamento_routes";
import PdvMovimentoRoute from "./pdv_movimento_routes";
import PdvOperadorRoute from "./pdv_operador_routes";
import PdvSangriaRoute from "./pdv_sangria_routes";
import PdvSuprimentoRoute from "./pdv_suprimento_routes";
import PdvTipoPagamentoRoute from "./pdv_tipo_pagamento_routes";
import PdvTotalTipoPagamentoRoute from "./pdv_total_tipo_pagamento_routes";
import PdvVendaCabecalhoRoute from "./pdv_venda_cabecalho_routes";
import PdvVendaDetalheRoute from "./pdv_venda_detalhe_routes";
import ProdutoRoute from "./produto_routes";
import ProdutoFichaTecnicaRoute from "./produto_ficha_tecnica_routes";
import ProdutoGrupoRoute from "./produto_grupo_routes";
import ProdutoImagemRoute from "./produto_imagem_routes";
import ProdutoPromocaoRoute from "./produto_promocao_routes";
import ProdutoSubgrupoRoute from "./produto_subgrupo_routes";
import ProdutoTipoRoute from "./produto_tipo_routes";
import ProdutoUnidadeRoute from "./produto_unidade_routes";
import TributCofinsRoute from "./tribut_cofins_routes";
import TributConfiguraOfGtRoute from "./tribut_configura_of_gt_routes";
import TributGrupoTributarioRoute from "./tribut_grupo_tributario_routes";
import TributIcmsCustomCabRoute from "./tribut_icms_custom_cab_routes";
import TributIcmsCustomDetRoute from "./tribut_icms_custom_det_routes";
import TributIcmsUfRoute from "./tribut_icms_uf_routes";
import TributIpiRoute from "./tribut_ipi_routes";
import TributIssRoute from "./tribut_iss_routes";
import TributOperacaoFiscalRoute from "./tribut_operacao_fiscal_routes";
import TributPisRoute from "./tribut_pis_routes";
import LoginRoute from './login_routes';

export const Route: Router = Router();

CfopRoute.allRoutes(Route);
ClienteRoute.allRoutes(Route);
ClienteFiadoRoute.allRoutes(Route);
ColaboradorRoute.allRoutes(Route);
CompraPedidoCabecalhoRoute.allRoutes(Route);
CompraPedidoDetalheRoute.allRoutes(Route);
ContadorRoute.allRoutes(Route);
ContasPagarRoute.allRoutes(Route);
ContasReceberRoute.allRoutes(Route);
EcfAliquotasRoute.allRoutes(Route);
EcfDocumentosEmitidosRoute.allRoutes(Route);
EcfE3Route.allRoutes(Route);
EcfImpressoraRoute.allRoutes(Route);
EcfLogTotaisRoute.allRoutes(Route);
EcfR01Route.allRoutes(Route);
EcfR02Route.allRoutes(Route);
EcfR03Route.allRoutes(Route);
EcfR06Route.allRoutes(Route);
EcfR07Route.allRoutes(Route);
EcfRecebimentoNaoFiscalRoute.allRoutes(Route);
EcfRelatorioGerencialRoute.allRoutes(Route);
EcfSintegra60aRoute.allRoutes(Route);
EcfSintegra60mRoute.allRoutes(Route);
EmpresaRoute.allRoutes(Route);
EmpresaCnaeRoute.allRoutes(Route);
EmpresaSegmentoRoute.allRoutes(Route);
FidelidadeHistoricoRoute.allRoutes(Route);
FidelidadeUtilizadoRoute.allRoutes(Route);
FornecedorRoute.allRoutes(Route);
IbptRoute.allRoutes(Route);
LogImportacaoRoute.allRoutes(Route);
NfcePlanoPagamentoRoute.allRoutes(Route);
NfeAcessoXmlRoute.allRoutes(Route);
NfeCabecalhoRoute.allRoutes(Route);
NfeCanaRoute.allRoutes(Route);
NfeCanaDeducoesSafraRoute.allRoutes(Route);
NfeCanaFornecimentoDiarioRoute.allRoutes(Route);
NfeConfiguracaoRoute.allRoutes(Route);
NfeCteReferenciadoRoute.allRoutes(Route);
NfeCupomFiscalReferenciadoRoute.allRoutes(Route);
NfeDeclaracaoImportacaoRoute.allRoutes(Route);
NfeDestinatarioRoute.allRoutes(Route);
NfeDetalheRoute.allRoutes(Route);
NfeDetalheImpostoCofinsRoute.allRoutes(Route);
NfeDetalheImpostoCofinsStRoute.allRoutes(Route);
NfeDetalheImpostoIcmsRoute.allRoutes(Route);
NfeDetalheImpostoIcmsUfdestRoute.allRoutes(Route);
NfeDetalheImpostoIiRoute.allRoutes(Route);
NfeDetalheImpostoIpiRoute.allRoutes(Route);
NfeDetalheImpostoIssqnRoute.allRoutes(Route);
NfeDetalheImpostoPisRoute.allRoutes(Route);
NfeDetalheImpostoPisStRoute.allRoutes(Route);
NfeDetEspecificoArmamentoRoute.allRoutes(Route);
NfeDetEspecificoCombustivelRoute.allRoutes(Route);
NfeDetEspecificoMedicamentoRoute.allRoutes(Route);
NfeDetEspecificoVeiculoRoute.allRoutes(Route);
NfeDuplicataRoute.allRoutes(Route);
NfeEmitenteRoute.allRoutes(Route);
NfeExportacaoRoute.allRoutes(Route);
NfeFaturaRoute.allRoutes(Route);
NfeImportacaoDetalheRoute.allRoutes(Route);
NfeInformacaoPagamentoRoute.allRoutes(Route);
NfeItemRastreadoRoute.allRoutes(Route);
NfeLocalEntregaRoute.allRoutes(Route);
NfeLocalRetiradaRoute.allRoutes(Route);
NfeNfReferenciadaRoute.allRoutes(Route);
NfeNumeroRoute.allRoutes(Route);
NfeNumeroInutilizadoRoute.allRoutes(Route);
NfeProcessoReferenciadoRoute.allRoutes(Route);
NfeProdRuralReferenciadaRoute.allRoutes(Route);
NfeReferenciadaRoute.allRoutes(Route);
NfeResponsavelTecnicoRoute.allRoutes(Route);
PdvCaixaRoute.allRoutes(Route);
PdvConfiguracaoRoute.allRoutes(Route);
PdvConfiguracaoBalancaRoute.allRoutes(Route);
PdvConfiguracaoLeitorSerialRoute.allRoutes(Route);
PdvFechamentoRoute.allRoutes(Route);
PdvMovimentoRoute.allRoutes(Route);
PdvOperadorRoute.allRoutes(Route);
PdvSangriaRoute.allRoutes(Route);
PdvSuprimentoRoute.allRoutes(Route);
PdvTipoPagamentoRoute.allRoutes(Route);
PdvTotalTipoPagamentoRoute.allRoutes(Route);
PdvVendaCabecalhoRoute.allRoutes(Route);
PdvVendaDetalheRoute.allRoutes(Route);
ProdutoRoute.allRoutes(Route);
ProdutoFichaTecnicaRoute.allRoutes(Route);
ProdutoGrupoRoute.allRoutes(Route);
ProdutoImagemRoute.allRoutes(Route);
ProdutoPromocaoRoute.allRoutes(Route);
ProdutoSubgrupoRoute.allRoutes(Route);
ProdutoTipoRoute.allRoutes(Route);
ProdutoUnidadeRoute.allRoutes(Route);
TributCofinsRoute.allRoutes(Route);
TributConfiguraOfGtRoute.allRoutes(Route);
TributGrupoTributarioRoute.allRoutes(Route);
TributIcmsCustomCabRoute.allRoutes(Route);
TributIcmsCustomDetRoute.allRoutes(Route);
TributIcmsUfRoute.allRoutes(Route);
TributIpiRoute.allRoutes(Route);
TributIssRoute.allRoutes(Route);
TributOperacaoFiscalRoute.allRoutes(Route);
TributPisRoute.allRoutes(Route);
LoginRoute.allRoutes(Route);